### ISSUE TITLE
Is this working correctly? You can select all the radiobuttons

### ISSUE THREAD

**Issue by suustenvoorde** [beaupd/chippr-beyco-newspage#12]
https://github.com/beaupd/chippr-beyco-newspage/blob/07804c91d490071dc7e4ca0b26cf2708ea0ae52e/src/pages/HomeBoudewijn/Home.js#L96

**Comment by boudewijnbout** [comment]
Yes this is not a groundbreaking bug, we focussed purely on making them work on the front-end side of the application. Nothing more than that.
